#!/usr/bin/env sh

testcase=$1
language=$(echo $testcase | awk -F'/' '{ print $2 }' )

java -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=y -cp compilers/$language/bin lfocc.compilers.$language.Main $testcase $testcase.out
