#!/usr/bin/env sh

testcases="none"
single="no"

if [ $# -eq 0 ]
then
    echo "Doing all testcases."
    testcases=$(find tests -name "*.lang")

    # reset fails
    echo -n > fails
elif [ $1 = "fails" ]
then
    if [ -e fails ]
    then
        echo "Doing only failed testcases."
        testcases=$(cat fails)
    else
        echo "Couldn't find fails file! Doing all testcases."
        testcases=$(find tests -name "*.lang")
    fi

    # reset fails
    echo -n > fails
else
    single="yes"
    testcases=$1
    echo "Doing testcase $testcases."
fi

testcases=$(echo "$testcases" | sed "s/\.lang$//" | sed "s/^\.\///")

pass=0
fail=0
total=0

# go over all testcases:
for testcase in $testcases
do

    language=$(echo $testcase | awk -F'/' '{ print $2 }')

    echo -n "Testcase $testcase ... "

    ret=0

    if [ -e  $testcase.compile.out ]
    then
        if [ "FAIL" = "$(cat $testcase.compile.out)" ]
        then
            ret=255
        fi
    fi

    output=$(java -enableassertions -cp compilers/$language/bin lfocc.compilers.$language.Main $testcase.lang $testcase.test.out 2>&1)

    if [ $? -ne $ret ]
    then
        echo "FAILURE!"
        echo "$output"
        fail=$((fail+1))
        if [ $single = "no" ]
        then
            echo $testcase >> fails
        fi
    else
        echo "OK!"
        pass=$((pass+1))
    fi

    if [ $single = "yes" ]
    then
        echo "$output"
    fi

    total=$((total+1))
done

echo
echo "Finished ($fail failed, $pass passed, $total in total)"
